### ISSUE TITLE
Fails to install on Fedora

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/egmde-snap#17]
Something goes wrong with the install hook:
```plain
$ snap install --classic --edge egmde
error: cannot perform the following tasks:
- Run install hook of "egmde" snap if present (run hook "install": 
-----
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Traceback (most recent call last):
  File "/usr/bin/dnf", line 57, in <module>
    from dnf.cli import main
  File "/usr/lib/python3.8/site-packages/dnf/__init__.py", line 30, in <module>
    import dnf.base
  File "/usr/lib/python3.8/site-packages/dnf/base.py", line 29, in <module>
    import libdnf.transaction
  File "/usr/lib64/python3.8/site-packages/libdnf/__init__.py", line 12, in <module>
    from . import conf
  File "/usr/lib64/python3.8/site-packages/libdnf/conf.py", line 13, in <module>
    from . import _conf
ImportError: /snap/core18/current/lib/x86_64-linux-gnu/librt.so.1: undefined symbol: __clock_nanosleep, version GLIBC_PRIVATE
-----)
```

**Comment by AlanGriffiths** [comment]
Fixed by #19
